# Generated by Django 5.2.4 on 2025-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='A_FAZER', max_length=20, verbose_name='Status'),
        ),
    ]
